universe = vanilla

output = ./logs/$(cluster).$(process).out 
error = ./logs/$(cluster).$(process).err 
log = ./logs/$(cluster).$(process).log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (OpSys == "LINUX" && Arch == "X86_64")
request_gpus = 0
request_cpus = 1
request_memory = 1GB
request_disk = 1MB

transfer_input_files = README.md,my.args
# transfer_executable = True
executable = run.sh
max_materialize = 2

arguments = "$(myargs)"
queue myargs from my.args